apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coolapp-prod
  name: coolapp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coolapp-prod
  strategy: {}
  template:
    metadata:
      labels:
        app: coolapp-prod
    spec:
      containers:
      - image: shobhan/docker-spring:1
        name: coolapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
