apiVersion: v1
kind: Service
metadata:
  labels:
    app: coolapp-prod-svc
  name: coolapp-prod-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30082
  selector:
    app: coolapp-prod
  type: NodePort
